language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.9"
  - "6.16"
  - "8.15"
  - "10.15"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 6 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run test-travis"
  - "test -z $(npm -ps ls eslint) || npm run-script lint"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
